runpod:
    base_path: /workspace/models

    checkpoints: checkpoints
    clip_vision: clip_vision
    configs: checkpoints
    vae: vae
    loras: loras
    upscale_models: upscale_models
    embeddings: embeddings
    hypernetworks: hypernetworks
    controlnet: controlnet
    ipadapter: ipadapter
    inpaint: inpaint
    style_models: style_models
    diffusion_models: diffusion_models
    text_encoders: text_encoders
